---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: spring-petclinic
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-petclinic
      tier: api-gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-petclinic
        tier: api-gateway
    spec:
      nodeSelector:
      #        cloud.google.com/gke-nodepool: node-pool-ane-ab
      containers:
        - image: {{ .Values.image.api_gateway }}
          imagePullPolicy: Always
          name: api-gateway
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: spring-petclinic
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-petclinic
      tier: customers
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-petclinic
        tier: customers
    spec:
      nodeSelector:
      #        cloud.google.com/gke-nodepool: node-pool-ane-ab
      containers:
        - image: {{ .Values.image.customers }}
          imagePullPolicy: Always
          name: customers
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOSTINFO
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: hostinfo
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: password
            - name: spring.profiles.active
              value: mysql
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
  labels:
    app: spring-petclinic
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-petclinic
      tier: vets
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-petclinic
        tier: vets
    spec:
      nodeSelector:
      #        cloud.google.com/gke-nodepool: node-pool-ane-ab
      containers:
        - image: {{ .Values.image.vets }}
          imagePullPolicy: Always
          name: vets
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOSTINFO
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: hostinfo
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: password
            - name: spring.profiles.active
              value: mysql
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
  labels:
    app: spring-petclinic
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-petclinic
      tier: visits
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-petclinic
        tier: visits
    spec:
      nodeSelector:
      #        cloud.google.com/gke-nodepool: node-pool-ane-ab
      containers:
        - image: {{ .Values.image.visits }}
          imagePullPolicy: Always
          name: visits
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOSTINFO
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: hostinfo
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: password
            - name: spring.profiles.active
              value: mysql
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
---
