---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
  name: mysql-config
  labels:
    app: spring-petclinic
data:
  hostinfo: {{ .Values.hostinfo }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
  name: mysql-credential
  labels:
    app: spring-petclinic
data:
  password: cGV0Y2xpbmlj # petclinic
  username: cGV0Y2xpbmlj # petclinic
---