---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"api-gateway-be"}}'
  name: api-gateway
  labels:
    app: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic
    tier: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"customer-be"}}'
  name: customers-service
  labels:
    app: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic
    tier: customers
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"vets-be"}}'
  name: vets-service
  labels:
    app: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic
    tier: vets
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"visits-be"}}'
  name: visits-service
  labels:
    app: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic
    tier: visits
---