apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/ryullulala/gcpzg-petclinic-chart'
    path: .
    targetRevision: HEAD
    helm:
      valueFiles:
        - Test.values.yaml

  destination:
    server: 'https://34.64.47.192'
    namespace: petclinic-msa

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
